version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo -e "\e[1;32m System Loaded by Mohammed \e[0m"
      - run: echo -e "\e[1;36m Commission: 1% \e[0m"
